# Generated by Django 5.1.2 on 2024-10-25 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('categoria', models.CharField(choices=[('visitante', 'Visitante'), ('funcionario', 'Funcionário')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='veiculos/')),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateField()),
                ('data_prevista_entrega', models.DateField()),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.usuario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.veiculo')),
            ],
        ),
    ]
