# Generated by Django 5.1.2 on 2024-10-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_alter_veiculo_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
