# Generated by Django 5.1.2 on 2024-10-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0003_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
