# Generated by Django 5.1.2 on 2024-10-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0004_veiculo_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
    ]
